first try
chugunse/java-shareit pull request #1
Opened 2023-03-12 08:20 UTC by chugunse

Настя привет)))
наконец то практика ))) я уж все позабыл пока балбесничал )))

2023-03-12 16:40 UTC, AnastasiyaFomkina requested changes
Отличная работа, молодец 👍

2023-03-12 16:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public Collection<UserDto> getAllUsers() {
Лучше заменить совсем абстрактный `Collection` на более узкий `List`. Так будет понятно, какую коллекцию мы ожидаем получить :)

2023-03-12 16:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-03-12 16:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +public class ErrorHandler {
🔥

2023-03-12 16:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exceptions/model/ErrorResponse.java
> +    public ErrorResponse(String error) {
Можно переписать с помощью @AllArgsConstructor и @Setter от lombok

2023-03-12 16:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                           @RequestHeader(value = "X-Sharer-User-Id") Long userId) {
Лучше вынести повторяющийся хэдер в константу, а лучше сразу в отдельный класс `Variables`, так как он нам еще понадобится в других классах

2023-03-12 16:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>   * TODO Sprint add-controllers.
Забыл удалить TODO

2023-03-12 16:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemRepository.java
> +        return items.values().stream().filter(item -> item.getOwner().getId().equals(userId))
```suggestion
        return items.values().stream()
           .filter(item -> item.getOwner().getId().equals(userId))
```

2023-03-12 17:16 UTC, chugunse commented on src/main/java/ru/practicum/shareit/item/service/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
это в следующем спринте ))))

2023-03-13 09:35 UTC, chugunse commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                           @RequestHeader(value = "X-Sharer-User-Id") Long userId) {
я правильно понимаю, что ты просишь создать отдельный класс с полями стринг которые будут хранить константы???
то есть это что то типо файла настроек 
и этому классу дать только геттеры и в эндпоинтах к ним обращаться

2023-03-13 14:31 UTC, closed without merging

2023-03-14 11:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                           @RequestHeader(value = "X-Sharer-User-Id") Long userId) {
Можешь, пожалуйста, писать в пачку, если не понимаешь что-то по ревью, чтобы я сразу посмотрела, а то до сюда я дохожу уже на стадии ревью :)